local trusts = {
    { id = 896, english = 'Shantotto', name = 'Shantotto' },
    { id = 897, english = 'Naji', name = 'Naji' },
    { id = 898, english = 'Kupipi', name = 'Kupipi' },
    { id = 899, english = 'Excenmille', name = 'Excenmille' },
    { id = 900, english = 'Ayame', name = 'Ayame' },
    { id = 901, english = 'Nanaa Mihgo', name = 'NanaaMihgo' },
    { id = 902, english = 'Curilla', name = 'Curilla' },
    { id = 903, english = 'Volker', name = 'Volker' },
    { id = 904, english = 'Ajido-Marujido', name = 'Ajido-Marujido' },
    { id = 905, english = 'Trion', name = 'Trion' },
    { id = 906, english = 'Zeid', name = 'Zeid' },
    { id = 907, english = 'Lion', name = 'Lion' },
    { id = 908, english = 'Tenzen', name = 'Tenzen' },
    { id = 909, english = 'Mihli Aliapoh', name = 'MihliAliapoh' },
    { id = 910, english = 'Valaineral', name = 'Valaineral' },
    { id = 911, english = 'Joachim', name = 'Joachim' },
    { id = 912, english = 'Naja Salaheem', name = 'NajaSalaheem' },
    { id = 913, english = 'Prishe', name = 'Prishe' },
    { id = 914, english = 'Ulmia', name = 'Ulmia' },
    { id = 915, english = 'Shikaree Z', name = 'ShikareeZ' },
    { id = 916, english = 'Cherukiki', name = 'Cherukiki' },
    { id = 917, english = 'Iron Eater', name = 'IronEater' },
    { id = 918, english = 'Gessho', name = 'Gessho' },
    { id = 919, english = 'Gadalar', name = 'Gadalar' },
    { id = 920, english = 'Rainemard', name = 'Rainemard' },
    { id = 921, english = 'Ingrid', name = 'Ingrid' },
    { id = 922, english = 'Lehko Habhoka', name = 'LehkoHabhoka' },
    { id = 923, english = 'Nashmeira', name = 'Nashmeira' },
    { id = 924, english = 'Zazarg', name = 'Zazarg' },
    { id = 925, english = 'Ovjang', name = 'Ovjang' },
    { id = 926, english = 'Mnejing', name = 'Mnejing' },
    { id = 927, english = 'Sakura', name = 'Sakura' },
    { id = 928, english = 'Luzaf', name = 'Luzaf' },
    { id = 929, english = 'Najelith', name = 'Najelith' },
    { id = 930, english = 'Aldo', name = 'Aldo' },
    { id = 931, english = 'Moogle', name = 'Moogle' },
    { id = 932, english = 'Fablinix', name = 'Fablinix' },
    { id = 933, english = 'Maat', name = 'Maat' },
    { id = 934, english = 'D. Shantotto', name = 'D.Shantotto' },
    { id = 935, english = 'Star Sibyl', name = 'StarSibyl' },
    { id = 936, english = 'Karaha-Baruha', name = 'Karaha-Baruha' },
    { id = 937, english = 'Cid', name = 'Cid' },
    { id = 938, english = 'Gilgamesh', name = 'Gilgamesh' },
    { id = 939, english = 'Areuhat', name = 'Areuhat' },
    { id = 940, english = 'Semih Lafihna', name = 'SemihLafihna' },
    { id = 941, english = 'Elivira', name = 'Elivira' },
    { id = 942, english = 'Noillurie', name = 'Noillurie' },
    { id = 943, english = 'Lhu Mhakaracca', name = 'LhuMhakaracca' },
    { id = 944, english = 'Ferreous Coffin', name = 'FerreousCoffin' },
    { id = 945, english = 'Lilisette', name = 'Lilisette' },
    { id = 946, english = 'Mumor', name = 'Mumor' },
    { id = 947, english = 'Uka Totlihn', name = 'UkaTotlihn' },
    { id = 948, english = 'Klara', name = 'Klara' },
    { id = 949, english = 'Romaa Mihgo', name = 'RomaaMihgo' },
    { id = 950, english = 'Kuyin Hathdenna', name = 'KuyinHathdenna' },
    { id = 951, english = 'Rahal', name = 'Rahal' },
    { id = 952, english = 'Koru-Moru', name = 'Koru-Moru' },
    { id = 953, english = 'Pieuje (UC)', name = 'Pieuje' },
    { id = 954, english = 'I. Shield (UC)', name = 'InvincibleShld' },
    { id = 955, english = 'Apururu (UC)', name = 'Apururu' },
    { id = 956, english = 'Jakoh (UC)', name = 'JakohWahcondalo' },
    { id = 957, english = 'Flaviria (UC)', name = 'Flaviria' },
    { id = 958, english = 'Babban', name = 'Babban' },
    { id = 959, english = 'Abenzio', name = 'Abenzio' },
    { id = 960, english = 'Rughadjeen', name = 'Rughadjeen' },
    { id = 961, english = 'Kukki-Chebukki', name = 'Kukki-Chebukki' },
    { id = 962, english = 'Margret', name = 'Margret' },
    { id = 963, english = 'Chacharoon', name = 'Chacharoon' },
    { id = 964, english = 'Lhe Lhangavo', name = 'LheLhangavo' },
    { id = 965, english = 'Arciela', name = 'Arciela' },
    { id = 966, english = 'Mayakov', name = 'Mayakov' },
    { id = 967, english = 'Qultada', name = 'Qultada' },
    { id = 968, english = 'Adelheid', name = 'Adelheid' },
    { id = 969, english = 'Amchuchu', name = 'Amchuchu' },
    { id = 970, english = 'Brygid', name = 'Brygid' },
    { id = 971, english = 'Mildaurion', name = 'Mildaurion' },
    { id = 972, english = 'Halver', name = 'Halver' },
    { id = 973, english = 'Rongelouts', name = 'Rongelouts' },
    { id = 974, english = 'Leonoyne', name = 'Leonoyne' },
    { id = 975, english = 'Maximilian', name = 'Maximilian' },
    { id = 976, english = 'Kayeel-Payeel', name = 'Kayeel-Payeel' },
    { id = 977, english = 'Robel-Akbel', name = 'Robel-Akbel' },
    { id = 978, english = 'Kupofried', name = 'Kupofried' },
    { id = 979, english = "Selh'teus", name = "Selh'teus" },
    { id = 980, english = 'Yoran-Oran (UC)', name = 'Yoran-Oran' },
    { id = 981, english = 'Sylvie (UC)', name = 'Sylvie' },
    { id = 982, english = 'Abquhbah', name = 'Abquhbah' },
    { id = 983, english = 'Balamor', name = 'Balamor' },
    { id = 984, english = 'August', name = 'August' },
    { id = 985, english = 'Rosulatia', name = 'Rosulatia' },
    { id = 986, english = 'Teodor', name = 'Teodor' },
    { id = 987, english = 'Ullegore', name = 'Ullegore' },
    { id = 988, english = 'Makki-Chebukki', name = 'Makki-Chebukki' },
    { id = 989, english = 'King of Hearts', name = 'KingOfHearts' },
    { id = 990, english = 'Morimar', name = 'Morimar' },
    { id = 991, english = 'Darrcuiln', name = 'Darrcuiln' },
    { id = 992, english = 'AAHM', name = 'ArkHM' },
    { id = 993, english = 'AAEV', name = 'ArkEV' },
    { id = 994, english = 'AAMR', name = 'ArkMR' },
    { id = 995, english = 'AATT', name = 'ArkTT' },
    { id = 996, english = 'AAGK', name = 'ArkGK' },
    { id = 997, english = 'Iroha', name = 'Iroha' },
    { id = 998, english = 'Ygnas', name = 'Ygnas' },
    { id = 1004, english = 'Excenmille [S]', name = 'Excenmille' },
    { id = 1005, english = 'Ayame (UC)', name = 'Ayame' },
    { id = 1006, english = 'Maat (UC)', name = 'Maat' },
    { id = 1007, english = 'Aldo (UC)', name = 'Aldo' },
    { id = 1008, english = 'Naja (UC)', name = 'NajaSalaheem' },
    { id = 1009, english = 'Lion II', name = 'Lion' },
    { id = 1010, english = 'Zeid II', name = 'Zeid' },
    { id = 1011, english = 'Prishe II', name = 'Prishe' },
    { id = 1012, english = 'Nashmeira II', name = 'Nashmeira' },
    { id = 1013, english = 'Lilisette II', name = 'Lilisette' },
    { id = 1014, english = 'Tenzen II', name = 'Tenzen' },
    { id = 1015, english = 'Mumor II', name = 'Mumor' },
    { id = 1016, english = 'Ingrid II', name = 'Ingrid' },
    { id = 1017, english = 'Arciela II', name = 'Arciela' },
    { id = 1018, english = 'Iroha II', name = 'Iroha' },
    { id = 1019, english = 'Shantotto II', name = 'Shantotto' },
    { id = 1002, english = 'Cornelia', name = 'Cornelia' },
    { id = 999, english = 'Monberaux', name = 'Monberaux' },
    { id = 1003, english = 'Matsui-P', name = 'Matsui-P' },
}

local function normalize(value)
    return tostring(value or ''):lower():gsub('[%s%p]', '')
end

local data = {
    list = trusts,
    names = {},
    by_key = {},
}

for _, trust in ipairs(trusts) do
    table.insert(data.names, trust.english)
    data.by_key[normalize(trust.english)] = trust
    data.by_key[normalize(trust.name)] = trust
end

table.sort(data.names)

return data
