local mage = require('job_helpers.mage_common')

return mage.create({
    job = 'RDM',
    cast_delay = 2.0,
    order = {
        'cure', 'cure2', 'cure3', 'cure4',
        'dia', 'dia2', 'dia3', 'bio', 'bio2', 'bio3',
        'slow', 'slow2', 'paralyze', 'paralyze2', 'blind', 'blind2',
        'addle', 'addle2', 'silence', 'gravity', 'gravity2', 'bind',
        'distract', 'distract2', 'distract3', 'frazzle', 'frazzle2', 'frazzle3',
        'poison', 'poison2', 'sleep', 'sleep2', 'break_spell', 'inundation',
        'haste', 'haste2', 'refresh', 'refresh2', 'refresh3', 'regen', 'regen2',
        'flurry', 'flurry2',
        'aquaveil', 'blink', 'stoneskin', 'phalanx', 'phalanx2',
        'blaze_spikes', 'ice_spikes', 'shock_spikes',
        'enfire', 'enblizzard', 'enaero', 'enstone', 'enthunder', 'enwater',
        'enfire2', 'enblizzard2', 'enaero2', 'enstone2', 'enthunder2', 'enwater2',
        'gain_str', 'gain_dex', 'gain_vit', 'gain_agi', 'gain_int', 'gain_mnd', 'gain_chr',
        'temper', 'temper2',
        'protect', 'protect2', 'protect3', 'protect4', 'protect5', 'shell', 'shell2', 'shell3', 'shell4', 'shell5',
    },
    cure_order = { 'cure4', 'cure3', 'cure2', 'cure' },
    raise_order = { 'raise2', 'raise' },
    spells = {
        cure = { name = 'Cure', type = 'cure', missing = 150 },
        cure2 = { name = 'Cure II', type = 'cure', missing = 350 },
        cure3 = { name = 'Cure III', type = 'cure', missing = 650 },
        cure4 = { name = 'Cure IV', type = 'cure', missing = 1100 },
        raise = { name = 'Raise', type = 'recovery' },
        raise2 = { name = 'Raise II', type = 'recovery' },
        dia = { name = 'Dia', type = 'enfeeble' },
        dia2 = { name = 'Dia II', type = 'enfeeble' },
        dia3 = { name = 'Dia III', type = 'enfeeble' },
        bio = { name = 'Bio', type = 'enfeeble' },
        bio2 = { name = 'Bio II', type = 'enfeeble' },
        bio3 = { name = 'Bio III', type = 'enfeeble' },
        slow = { name = 'Slow', type = 'enfeeble' },
        slow2 = { name = 'Slow II', type = 'enfeeble' },
        paralyze = { name = 'Paralyze', type = 'enfeeble' },
        paralyze2 = { name = 'Paralyze II', type = 'enfeeble' },
        blind = { name = 'Blind', type = 'enfeeble' },
        blind2 = { name = 'Blind II', type = 'enfeeble' },
        addle = { name = 'Addle', type = 'enfeeble' },
        addle2 = { name = 'Addle II', type = 'enfeeble' },
        silence = { name = 'Silence', type = 'enfeeble' },
        gravity = { name = 'Gravity', type = 'enfeeble' },
        gravity2 = { name = 'Gravity II', type = 'enfeeble' },
        bind = { name = 'Bind', type = 'enfeeble' },
        distract = { name = 'Distract', type = 'enfeeble' },
        distract2 = { name = 'Distract II', type = 'enfeeble' },
        distract3 = { name = 'Distract III', type = 'enfeeble' },
        frazzle = { name = 'Frazzle', type = 'enfeeble' },
        frazzle2 = { name = 'Frazzle II', type = 'enfeeble' },
        frazzle3 = { name = 'Frazzle III', type = 'enfeeble' },
        poison = { name = 'Poison', type = 'enfeeble' },
        poison2 = { name = 'Poison II', type = 'enfeeble' },
        sleep = { name = 'Sleep', type = 'enfeeble' },
        sleep2 = { name = 'Sleep II', type = 'enfeeble' },
        break_spell = { name = 'Break', type = 'enfeeble' },
        inundation = { name = 'Inundation', type = 'enfeeble' },
        haste = { name = 'Haste', type = 'buff_tier' },
        haste2 = { name = 'Haste II', type = 'buff_tier' },
        refresh = { name = 'Refresh', type = 'buff_tier' },
        refresh2 = { name = 'Refresh II', type = 'buff_tier' },
        refresh3 = { name = 'Refresh III', type = 'buff_tier' },
        regen = { name = 'Regen', type = 'buff_tier' },
        regen2 = { name = 'Regen II', type = 'buff_tier' },
        flurry = { name = 'Flurry', type = 'buff_tier' },
        flurry2 = { name = 'Flurry II', type = 'buff_tier' },
        aquaveil = { name = 'Aquaveil', type = 'buff' },
        blink = { name = 'Blink', type = 'buff' },
        stoneskin = { name = 'Stoneskin', type = 'buff' },
        phalanx = { name = 'Phalanx', type = 'buff' },
        phalanx2 = { name = 'Phalanx II', type = 'buff' },
        blaze_spikes = { name = 'Blaze Spikes', type = 'buff_tier' },
        ice_spikes = { name = 'Ice Spikes', type = 'buff_tier' },
        shock_spikes = { name = 'Shock Spikes', type = 'buff_tier' },
        enfire = { name = 'Enfire', type = 'buff_tier' },
        enblizzard = { name = 'Enblizzard', type = 'buff_tier' },
        enaero = { name = 'Enaero', type = 'buff_tier' },
        enstone = { name = 'Enstone', type = 'buff_tier' },
        enthunder = { name = 'Enthunder', type = 'buff_tier' },
        enwater = { name = 'Enwater', type = 'buff_tier' },
        enfire2 = { name = 'Enfire II', type = 'buff_tier' },
        enblizzard2 = { name = 'Enblizzard II', type = 'buff_tier' },
        enaero2 = { name = 'Enaero II', type = 'buff_tier' },
        enstone2 = { name = 'Enstone II', type = 'buff_tier' },
        enthunder2 = { name = 'Enthunder II', type = 'buff_tier' },
        enwater2 = { name = 'Enwater II', type = 'buff_tier' },
        gain_str = { name = 'Gain-STR', type = 'buff_tier' },
        gain_dex = { name = 'Gain-DEX', type = 'buff_tier' },
        gain_vit = { name = 'Gain-VIT', type = 'buff_tier' },
        gain_agi = { name = 'Gain-AGI', type = 'buff_tier' },
        gain_int = { name = 'Gain-INT', type = 'buff_tier' },
        gain_mnd = { name = 'Gain-MND', type = 'buff_tier' },
        gain_chr = { name = 'Gain-CHR', type = 'buff_tier' },
        temper = { name = 'Temper', type = 'buff_tier' },
        temper2 = { name = 'Temper II', type = 'buff_tier' },
        protect = { name = 'Protect', type = 'buff_tier' },
        protect2 = { name = 'Protect II', type = 'buff_tier' },
        protect3 = { name = 'Protect III', type = 'buff_tier' },
        protect4 = { name = 'Protect IV', type = 'buff_tier' },
        protect5 = { name = 'Protect V', type = 'buff_tier' },
        shell = { name = 'Shell', type = 'buff_tier' },
        shell2 = { name = 'Shell II', type = 'buff_tier' },
        shell3 = { name = 'Shell III', type = 'buff_tier' },
        shell4 = { name = 'Shell IV', type = 'buff_tier' },
        shell5 = { name = 'Shell V', type = 'buff_tier' },
    },
    enfeebles = {
        { effect = 'dia_bio', spells = { 'dia3', 'dia2', 'dia', 'bio3', 'bio2', 'bio' }, duration = 180 },
        { effect = 'slow', spells = { 'slow2', 'slow' }, duration = 180 },
        { effect = 'paralyze', spells = { 'paralyze2', 'paralyze' }, duration = 120 },
        { effect = 'blind', spells = { 'blind2', 'blind' }, duration = 180 },
        { effect = 'addle', spells = { 'addle2', 'addle' }, duration = 180 },
        { effect = 'silence', spells = { 'silence' }, duration = 120 },
        { effect = 'gravity', spells = { 'gravity2', 'gravity' }, duration = 120 },
        { effect = 'bind', spells = { 'bind' }, duration = 60 },
        { effect = 'distract', spells = { 'distract3', 'distract2', 'distract' }, duration = 180 },
        { effect = 'frazzle', spells = { 'frazzle3', 'frazzle2', 'frazzle' }, duration = 180 },
        { effect = 'poison', spells = { 'poison2', 'poison' }, duration = 120 },
        { effect = 'sleep', spells = { 'sleep2', 'sleep' }, duration = 90 },
        { effect = 'break', spells = { 'break_spell' }, duration = 30 },
        { effect = 'inundation', spells = { 'inundation' }, duration = 180 },
    },
    tier_options = {
        {
            setting = 'protect_tier',
            label = 'Protect Spell',
            target_group = 'protect',
            target_label = 'Protect target slots',
            default = 'disabled',
            options = {
                { key = 'protect', name = 'Protect' },
                { key = 'protect2', name = 'Protect II' },
                { key = 'protect3', name = 'Protect III' },
                { key = 'protect4', name = 'Protect IV' },
                { key = 'protect5', name = 'Protect V' },
            },
        },
        {
            setting = 'shell_tier',
            label = 'Shell Spell',
            target_group = 'shell',
            target_label = 'Shell target slots',
            default = 'disabled',
            options = {
                { key = 'shell', name = 'Shell' },
                { key = 'shell2', name = 'Shell II' },
                { key = 'shell3', name = 'Shell III' },
                { key = 'shell4', name = 'Shell IV' },
                { key = 'shell5', name = 'Shell V' },
            },
        },
        {
            setting = 'haste_tier',
            label = 'Haste Spell',
            target_group = 'haste',
            target_label = 'Haste target slots',
            default = 'disabled',
            options = {
                { key = 'haste', name = 'Haste' },
                { key = 'haste2', name = 'Haste II' },
            },
        },
        {
            setting = 'refresh_tier',
            label = 'Refresh Spell',
            target_group = 'refresh',
            target_label = 'Refresh target slots',
            default = 'disabled',
            options = {
                { key = 'refresh', name = 'Refresh' },
                { key = 'refresh2', name = 'Refresh II' },
                { key = 'refresh3', name = 'Refresh III' },
            },
        },
        {
            setting = 'regen_tier',
            label = 'Regen Spell',
            target_group = 'regen',
            target_label = 'Regen target slots',
            default = 'disabled',
            options = {
                { key = 'regen', name = 'Regen' },
                { key = 'regen2', name = 'Regen II' },
            },
        },
        {
            setting = 'flurry_tier',
            label = 'Flurry Spell',
            target_group = 'flurry',
            target_label = 'Flurry target slots',
            default = 'disabled',
            options = {
                { key = 'flurry', name = 'Flurry' },
                { key = 'flurry2', name = 'Flurry II' },
            },
        },
        {
            setting = 'spikes_tier',
            label = 'Spikes Spell',
            default = 'disabled',
            options = {
                { key = 'blaze_spikes', name = 'Blaze Spikes' },
                { key = 'ice_spikes', name = 'Ice Spikes' },
                { key = 'shock_spikes', name = 'Shock Spikes' },
            },
        },
        {
            setting = 'enspell_tier',
            label = 'Enspell',
            default = 'disabled',
            options = {
                { key = 'enfire', name = 'Enfire' },
                { key = 'enblizzard', name = 'Enblizzard' },
                { key = 'enaero', name = 'Enaero' },
                { key = 'enstone', name = 'Enstone' },
                { key = 'enthunder', name = 'Enthunder' },
                { key = 'enwater', name = 'Enwater' },
                { key = 'enfire2', name = 'Enfire II' },
                { key = 'enblizzard2', name = 'Enblizzard II' },
                { key = 'enaero2', name = 'Enaero II' },
                { key = 'enstone2', name = 'Enstone II' },
                { key = 'enthunder2', name = 'Enthunder II' },
                { key = 'enwater2', name = 'Enwater II' },
            },
        },
        {
            setting = 'gain_tier',
            label = 'Gain Spell',
            default = 'disabled',
            options = {
                { key = 'gain_str', name = 'Gain-STR' },
                { key = 'gain_dex', name = 'Gain-DEX' },
                { key = 'gain_vit', name = 'Gain-VIT' },
                { key = 'gain_agi', name = 'Gain-AGI' },
                { key = 'gain_int', name = 'Gain-INT' },
                { key = 'gain_mnd', name = 'Gain-MND' },
                { key = 'gain_chr', name = 'Gain-CHR' },
            },
        },
        {
            setting = 'temper_tier',
            label = 'Temper Spell',
            default = 'disabled',
            options = {
                { key = 'temper', name = 'Temper' },
                { key = 'temper2', name = 'Temper II' },
            },
        },
    },
    target_groups = {
        { group = 'phalanx2', label = 'Phalanx II target slots' },
    },
    buffs = {
        {
            key = 'protect_tier',
            group = 'protect',
            buff_id = 40,
            interval = 1800,
            tier_setting = 'protect_tier',
            tiers = {
                protect = 'Protect',
                protect2 = 'Protect II',
                protect3 = 'Protect III',
                protect4 = 'Protect IV',
                protect5 = 'Protect V',
            },
        },
        {
            key = 'shell_tier',
            group = 'shell',
            buff_id = 41,
            interval = 1800,
            tier_setting = 'shell_tier',
            tiers = {
                shell = 'Shell',
                shell2 = 'Shell II',
                shell3 = 'Shell III',
                shell4 = 'Shell IV',
                shell5 = 'Shell V',
            },
        },
        {
            key = 'haste_tier',
            group = 'haste',
            buff_id = 33,
            interval = 150,
            tier_setting = 'haste_tier',
            tiers = { haste = 'Haste', haste2 = 'Haste II' },
        },
        {
            key = 'refresh_tier',
            group = 'refresh',
            buff_id = 43,
            interval = 150,
            tier_setting = 'refresh_tier',
            tiers = {
                refresh = 'Refresh',
                refresh2 = 'Refresh II',
                refresh3 = 'Refresh III',
            },
        },
        {
            key = 'regen_tier',
            group = 'regen',
            buff_id = 42,
            interval = 60,
            tier_setting = 'regen_tier',
            tiers = { regen = 'Regen', regen2 = 'Regen II' },
        },
        {
            key = 'flurry_tier',
            group = 'flurry',
            interval = 150,
            tier_setting = 'flurry_tier',
            tiers = { flurry = 'Flurry', flurry2 = 'Flurry II' },
        },
        { key = 'aquaveil', name = 'Aquaveil', target = 'self', interval = 300 },
        { key = 'blink', name = 'Blink', target = 'self', interval = 300 },
        { key = 'stoneskin', name = 'Stoneskin', target = 'self', interval = 300 },
        { key = 'phalanx', name = 'Phalanx', target = 'self', interval = 180 },
        { key = 'phalanx2', name = 'Phalanx II', group = 'phalanx2', interval = 180 },
        {
            key = 'spikes_tier',
            target = 'self',
            interval = 180,
            tier_setting = 'spikes_tier',
            tiers = {
                blaze_spikes = 'Blaze Spikes',
                ice_spikes = 'Ice Spikes',
                shock_spikes = 'Shock Spikes',
            },
        },
        {
            key = 'enspell_tier',
            target = 'self',
            interval = 180,
            tier_setting = 'enspell_tier',
            tiers = {
                enfire = 'Enfire', enblizzard = 'Enblizzard',
                enaero = 'Enaero', enstone = 'Enstone',
                enthunder = 'Enthunder', enwater = 'Enwater',
                enfire2 = 'Enfire II', enblizzard2 = 'Enblizzard II',
                enaero2 = 'Enaero II', enstone2 = 'Enstone II',
                enthunder2 = 'Enthunder II', enwater2 = 'Enwater II',
            },
        },
        {
            key = 'gain_tier',
            target = 'self',
            interval = 300,
            tier_setting = 'gain_tier',
            tiers = {
                gain_str = 'Gain-STR', gain_dex = 'Gain-DEX',
                gain_vit = 'Gain-VIT', gain_agi = 'Gain-AGI',
                gain_int = 'Gain-INT', gain_mnd = 'Gain-MND',
                gain_chr = 'Gain-CHR',
            },
        },
        {
            key = 'temper_tier',
            target = 'self',
            interval = 180,
            tier_setting = 'temper_tier',
            tiers = { temper = 'Temper', temper2 = 'Temper II' },
        },
    },
})
